### ISSUE TITLE
GPIO monitor multiple PINs setup

### ISSUE THREAD

**Issue by GOVEN007** [matthuisman/service.gpio.monitor#1]
It would be nice to setup more that one PIN in GPIO Monitor add-on.
(This would help in building Keyboards/Buttons controlling KODI)

**Comment by matthuisman** [comment]
I have started work on this:
https://github.com/matthuisman/service.gpio.monitor/tree/rewrite

**Comment by matthuisman** [comment]
Good progress on this today :)
Hopefully have a new release within next day.

You will be able to have functions that run on both rising and falling edges.
You will be able to select internal pull up or down.
And multiple functions per pin / edge as well.

**Comment by matthuisman** [comment]
https://github.com/matthuisman/service.gpio.monitor/commit/005c95488f337764eb38aec585b650bf50621b43

**Comment by GOVEN007** [comment]
Thank you!

**Comment by matthuisman** [comment]
Working on another re-write which uses gpiozero library to make it all a bit more simple.
It also adds ability to have on hold functions.
It also will show the status of pins so you can easily see any errors (eg in below image)

Multiple commands will be done using a |

![screenshot000](https://user-images.githubusercontent.com/6225961/46514747-3564b780-c8bc-11e8-9964-374f47eb1cb4.png)

**Comment by Fluvoxamin** [comment]
Hello Matt,
how settled my configuration and my circuit
I want a reboot when pressing the button

![20181014_105520](https://user-images.githubusercontent.com/44069674/46914563-e4ca1a00-cf9f-11e8-9a59-f4bf4345e137.jpg)
![20181014_103559](https://user-images.githubusercontent.com/44069674/46914562-e4ca1a00-cf9f-11e8-885c-1d1aefc7c61f.jpg)

**Comment by matthuisman** [comment]
@Fluvoxamin
The "when pressed" should be "Reboot" not "Action(Reboot)"

**Comment by Fluvoxamin** [comment]
Hello Matt,

now it works! Quick test was very successful!
Thank you very mutch for your Add-On and your help!

Could you please post here adress of your repository. The instructions from your side have taken out.

Thanks again!

Fluvoxamin

**Comment by matthuisman** [comment]
@Fluvoxamin

I will be updating that post hopefully today and bringing it back "live".
I took it down as it's out-of-date now.

**Comment by Fluvoxamin** [comment]
Ok ill wait ;)

**Comment by matthuisman** [comment]
@Fluvoxamin 

Post is now live:
https://www.matthuisman.nz/2016/11/gpio-monitor-service-kodi-add-on.html

**Comment by Fluvoxamin** [comment]
> @Fluvoxamin
> 
> Post is now live:
> https://www.matthuisman.nz/2016/11/gpio-monitor-service-kodi-add-on.html

Thank you Matt. Now it is for beginners. Very good tutorial.

**Comment by Fluvoxamin** [comment]
Hello Matt,

I would need your help again, please. I have done it according to your instructions, but the following happens:
I used 4 buttons with: Action (Up), Action (Down), Action (Left), Action (Right). The problem is that Kodi executes only the last entry, no matter which button I press. For example after the button (Right) I place a button (Play) then for Kodi only play, even if I press the button Action (Down).
Please help me there something goes wrong again.
This is my Configuration.

![20181111_112632](https://user-images.githubusercontent.com/44069674/48311892-be030180-e5a6-11e8-87f8-4d21316f8f1e.jpg)
![20181111_112648](https://user-images.githubusercontent.com/44069674/48311893-be030180-e5a6-11e8-9eed-e852d745ec85.jpg)
Fluvoxamin

**Comment by matthuisman** [comment]
@Fluvoxamin
Please show your circuit with buttons connected

**Comment by matthuisman** [comment]
@Fluvoxamin 
Fixed: https://github.com/matthuisman/service.gpio.monitor/commit/3b0c5c2d7e7547a11a0ef492c78202e49a6723eb

Just pushed 0.8.0 of the add-on with this fix

**Comment by Fluvoxamin** [comment]
Sorry Matt, but that does not update it
![20181112_002405](https://user-images.githubusercontent.com/44069674/48319745-1ae7d180-e612-11e8-872e-74d9e258ff76.jpg)
![20181112_002435](https://user-images.githubusercontent.com/44069674/48319746-1ae7d180-e612-11e8-92ee-9e51cc320ed7.jpg)
![20181112_002557](https://user-images.githubusercontent.com/44069674/48319747-1ae7d180-e612-11e8-993f-53dd08e17d98.jpg)

**Comment by matthuisman** [comment]
@Fluvoxamin
You need to go to my REPO.
Open context menu and click "Check for updates"

**Comment by Fluvoxamin** [comment]
Is not this on the picture your repo?
![](https://user-images.githubusercontent.com/44069674/48319747-1ae7d180-e612-11e8-993f-53dd08e17d98.jpg)

**Comment by Fluvoxamin** [comment]
I have done update on GPIO Monitor and MattHuisman.nz repository
Can it be due to the time difference? Or is it nonsense?

**Comment by matthuisman** [comment]
Please see my image.
Your not in correct area

**Comment by penjats** [comment]
Hi Matt,
How could I add button GPIO27, this is the "left" on the joystick of the arcade control... and it is not in the button list

![ief9vdv](https://user-images.githubusercontent.com/45108498/48664208-8ced6a00-ea9b-11e8-92b9-0250d1604e20.jpg)

![img_20181117_190520](https://user-images.githubusercontent.com/45108498/48664253-1735ce00-ea9c-11e8-850e-20005a40c666.jpg)

Thank you.

**Comment by matthuisman** [comment]
@penjats
Fixed https://github.com/matthuisman/service.gpio.monitor/commit/2f360ecc978f2c45cda7c30c148555559ead4adc (v 0.9.0 of the add-on)
