### ISSUE TITLE
gpio monitor killing Kodi (armv6)

### ISSUE THREAD

**Issue by jasper1040** [matthuisman/service.gpio.monitor#2]
[kodi_crashlog-20181217_065923.log](https://github.com/matthuisman/service.gpio.monitor/files/2686639/kodi_crashlog-20181217_065923.log)

As soon as I install GPIO Monitor into Kodi 17.6 it causes Kodi to crash after a few seconds.   Rebooting/restarting Kodi doesn’t help.   Same results with multiple installations of Raspbian Stretch full and Raspbian Stretch Lite.    Kodi won’t even run long enough for me to attempt any GPIO configuration or even disable or uninstall GPIO Monitor.    Uninstall/reinstall of Kodi doesn’t make this addon go way.  Same results for all 6 attempts with from scratch reloads of operating system and Kodi.   I’m installing GPIO monitor from zip file - service.gpio.monitor-latest.zip.   I’m been fighting this for weeks on a project that was supposed to be a Christmas present for my Mom so I’m running out of time.   I’ve been trying other alternatives but none look very hopeful for using physical wired buttons to issue keystrokes into Kodi.  Attached is one of the Kodi-crash log files.

**Comment by matthuisman** [comment]
As per here:
https://www.matthuisman.nz/2018/10/gpio-monitor-kodi-add-on.html

Runs only on LibreELEC / OSMC or XBIAN.
Is not made for or tested with Raspbian.

You don't need to reload the OS.
To remove an add-on, remove it from ~/.kodi/addons

**Comment by jasper1040** [comment]
Forgot to mention, I actually started with OSMC with the same crash results but thought there was little hope of being able to tweak OSMC in hopes of getting it to work.   However, I can try that one again if you really think it will work...   Haven't tried LibreELEC yet.

**Comment by matthuisman** [comment]
It should work fine in both OSMC & LibreELEC.
Install this before ANY thing else.
Some "dody" add-ons can cause all sorts of issues

**Comment by jasper1040** [comment]
No other add-ons.    Making a new image now.   I used the zip because I wasn't seeing your repo.   Will look harder.   Thanks!

**Comment by matthuisman** [comment]
Oh, that could be the issue then :)
There is a bit of "generation" between source code and released add-on.

Here is a zip you can use:
https://github.com/matthuisman/kodi-repo/raw/master/service.gpio.monitor/service.gpio.monitor-latest.zip

**Comment by jasper1040** [comment]
I'm not seeing a "MattHuisman.nz Repository"   Which category should it be in?   I installed from the .zip in your link.   After a few seconds I simply get a :(   and OSMC reboots.  I get a :(    I try to run the add-on and I get a :(      If I just let it sit, my pi is just in a looping cycle of crashing with a :(  and restarting.

**Comment by jasper1040** [comment]
Should I try an older version of OSMC?  I'm using OSMC_TGT_rbp1_20181101.img

**Comment by matthuisman** [comment]
Oh, your using a Raspberry Pi 1??

**Comment by jasper1040** [comment]
Just tried LibreELEC and the results are basically the same as with OSMC except that it crashes faster and I just get a blank screen rather than a "frowny" face.   Using the .zip you sent the link for because I still don't see "MattHuisman.nz Repository" as a choice.

**Comment by jasper1040** [comment]
Yes.  I have models B1 and B+ V1

**Comment by jasper1040** [comment]
Based on the tone of your last response, I borrowed a Pi 3 from a friend and your add-on works fine on that pi from the .zip you sent.     Any chance that an older or modified version is available that will work on a Pi 1?   Or do I just have to buy a new pi?    I was hoping this would be a good use for my stash of old pi's.

thanks,
Ken

**Comment by matthuisman** [comment]
working on it now.
My latest commit should make it work on older Pi's (armv6)
https://github.com/matthuisman/service.gpio.monitor/commit/a34360402b62fdbf118a808a8c0c02964a7b67e0

Have tested on a Pi1A+ and all OK.
Just need to test on a Pi3 to make sure that didn't break.

Once OK, I'll post a link to the new download

**Comment by matthuisman** [comment]
Success :)

Download latest version here:
https://github.com/matthuisman/kodi-repo/raw/master/service.gpio.monitor/service.gpio.monitor-latest.zip

Let me know how it goes :)

**Comment by matthuisman** [comment]
It also now (v0.11.0) supports Raspbian.
Get with same above link :)

**Comment by jasper1040** [comment]
Looking very hopeful with OSMC.   Configuration some buttons now....   THANKS!    Not sure which operating system version I will end up with but I will try several and let you know the results.

**Comment by matthuisman** [comment]
Great :)
If you want to automatically get updates etc, then install my REPO first.
Then install the add-on via the repo.

Follow this to install my repo:
https://www.youtube.com/watch?v=LWYg6WS1WoU

Once the repo is installed, you can install the add-on via KODI (no need to download zip).
