### ISSUE TITLE
Time delayed gpio shutdown

### ISSUE THREAD

**Issue by Maju3** [matthuisman/service.gpio.monitor#5]
I have installed a raspberry pi3 with libreelec in my car.
Now gpio monitor is a great tool to shutdown the pi with cars ignition.
I use a simple 12volt relay triggered by the cars ignition.
So the "NC" contacts of the relay are connected to a gpio pin and to ground of the gpio pin header.
This means when the cars ignition is OFF then the gpio pin goes LOW (gpio to ground) and the raspberry pi shuts down.

Now i think for short stops it would be cool to have a delayed shutdown.
This means the gpio monitor should initiate a shutdown when the gpio pin is LOW for 5 minutes.

Is this possible?
The delay time should be setable in seconds.
Lets say from 10 seconds to 10 minutes.

Thank you

**Comment by matthuisman** [comment]
Use onhold and set hold time to 5 minutes should do it.

**Comment by Maju3** [comment]
Wow thanks for your quick reply !
I should read better.
"Hold time" is exactly what i need for a delayed shutdown :)
Thanks a lot :)

**Comment by matthuisman** [comment]
No worries :)

**Comment by Maju3** [comment]
Another question.
Is it possible to include a "screen backlight off" function?
I use the original raspberry 7" touchscreen.

I think about following.
Gpio 10 as "ignition car pin"

Gpio 10 is LOW for 10 seconds -> screen backlight goes off
Gpio 10 is LOW for 5 minutes -> raspberry pi shutdown.

So gpio 10 has 2 time based functions.

**Comment by Maju3** [comment]
Instead of "screen backlight off" when a BLACK screensaver jumps in after 10 seconds would be the same.
My goal is just not to get attention from the wrong people after leaving my car ;)
So it is better to have a black screen.

**Comment by matthuisman** [comment]
You'd need to find the kodi built-in function to do that.

As for two held functions at different times, not possible.

You could try have onpress with a large debounce value for the first
function. Then onheld with held time value for second function.

You can have multiple functions at same time using a pipe | between them

**Comment by Maju3** [comment]
Thanks again!
I think i just use 2 different gpio pins.
One for activate screensaver with hold time 10 secons.
The other with hold time 5 minutes for shutdown.

That should fit my needs pretty good i mean.

Keep up your great work man and thanks for your quick replies:)

**Comment by matthuisman** [comment]
No worries :)
Yes, using two pins just both connected to same wire is a great way to have multiple hold functions :)

**Comment by Maju3** [comment]
Absolutely!

Relay NC contact 1  -> GPIO17/GPIO18
Relay NC contact 2  ->  GPIO GROUND

Relay is triggered by ignition of car.
Ignition OFF -> gpio is LOW :)

And with the hold button time i get my delay of shutdown and screensaver:)

works perfectly man;)

**Comment by matthuisman** [comment]
COOL!
I guess your using "ActivateScreensaver" & "ShutDown" built-ins?

For the official 7" display, the below may also work for turning off the backlight:
`System.Exec(echo 0 > /sys/class/backlight/rpi_backlight/bl_power)`
https://forum.kodi.tv/showthread.php?tid=289480

**Comment by Maju3** [comment]
Exactly.
"Activatescreensaver" and "shutdown" is what i use.

**Comment by matthuisman** [comment]
Do you then disconnect power completely to the Pi (via relay)?
I think even when shutdown, it will still draw quite a bit of current and eventually flatten the battery if left for too long

**Comment by Maju3** [comment]
Good find, Sir :)
i will try this "backlight off screensaver" addon next days.

Thanks mate!

**Comment by Maju3** [comment]
Yes
I have a M3ATX psu from old windows based car pc days;)

just google "m3atx psu".
It has jumper settings for hardoff.
I have set it now to 15 minutes hardoff.

**Comment by Maju3** [comment]
This means after ignition is off then after 15 mins the m3atx cuts the power to the rpi completely

**Comment by matthuisman** [comment]
Very good.

Something to keep in mind with turning off the display backlight is that you won't be able to get it back on until the Pi is restarted. Where as a screensaver will turn off if you navigate.

**Comment by Maju3** [comment]
Need to try a bit more.
Maybe i set the hold button for shutdown to 14 minutes.
Then the rpi has 1 minute for clean shutdown before the m3atx cuts the power.
Should work i mean and then i get a better Boot/Shutdown behaviour.

**Comment by Maju3** [comment]
Uuuuhhh yes you are right.
Then the backlight off is not so good :(

Wait.....
Is it possible like this:
Gpio low->screensaver on
Gpio high->screensaver off

?

**Comment by matthuisman** [comment]
Behind the scenes, GPIO Zero Button is used:
https://gpiozero.readthedocs.io/en/stable/api_input.html#button

You could use a third pin with pullup set to True.
(I'm guessing your other buttons are pullup False?)
So when it's pulled low, it will activate the function (screensaver on)

**Comment by Maju3** [comment]
Damned yes.
I forgot to set pull up to "true"

Just for my understanding.....
Gpio 17 for screensaver with 10 seconds delay:

Pin=gpio17
When held=ActivateScreensaver
Hold time=10


Now when gpio17 is connected to ground it has LOW state and after 10 seconds (held time) the screensaver is on.
Now when i turn on ignition of my car the gpio is pulled up to HIGH state and the screensaver goes off.
Correct?

**Comment by matthuisman** [comment]
I don't there is a turn off screensaver function.
I'd use a another pin that just does some builtin function that would deactibate the screensaver (eg. action(up))

**Comment by Maju3** [comment]
Okay sir:)
then i change my mind.
Instead of "held button" i will do following:

When pressed=ActivateScreensaver
When released=Action(up)

in this case the screensaver goes on directly after ignition is off.
But this way i get a toggle function(screensaver on/off)

pretty cool:)
i try this next days.

Thanks for your time helping out a newbie.
Pretty cool to chat with you:)

**Comment by matthuisman** [comment]
No worries.

There should be a builtin you can to stop the screensaver without actually moving the navigation.
Maybe try Container.Refresh or ActivateWindow(10000)

**Comment by Maju3** [comment]
Yes you are right.
I try a bit more in a few days.
BTW if you are interested i use this skin....
https://www.tapatalk.com/groups/engineeringdiy/skin-mod-carpc-xtouch-t633.html?sid=4e74dca6373c4731138a9e4504876159

**Comment by Maju3** [comment]
Scroll down a bit then you see the screenshots.
Anyway your gpio-monitor is really amazing.
Especially for people who are not familiar with gpio stuff at all.
Now with your help i am able to integrate hardware buttons to control kodi :)
This is much better as typing on the touchscreen in a moving car.
