### ISSUE TITLE
Lirc Possibility

### ISSUE THREAD

**Issue by Odianosen25** [matthuisman/service.gpio.monitor#6]
Hello @matthuisman,

I just came across your addon, and thanks for the work on it.

Please I have a special use case, whereby I want to be able to control IR devices via a plugin. Do you think it’s something that can be done via your addon?

If not, can you kindly point me in the right direction? Just like in your addon, I want to be able to make an external call using Kodi’s api, and it will fire an IR remote single from one of the configured Lirc codes.

Kind regards

**Comment by matthuisman** [comment]
@Odianosen25

This add-on responds to GPIO inputs.
It is not for outputs.

You'd need to write something your self I think.
This is usually the case for any "special cases".
